# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.26

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/kani/Desktop/Podrum-main

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/kani/Desktop/Podrum-main

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/kani/Desktop/Podrum-main/CMakeFiles /home/kani/Desktop/Podrum-main//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/kani/Desktop/Podrum-main/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named PodrumR4

# Build rule for target.
PodrumR4: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 PodrumR4
.PHONY : PodrumR4

# fast build rule for target.
PodrumR4/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PodrumR4.dir/build.make CMakeFiles/PodrumR4.dir/build
.PHONY : PodrumR4/fast

cbinarystream/binary_stream.o: cbinarystream/binary_stream.c.o
.PHONY : cbinarystream/binary_stream.o

# target to build an object file
cbinarystream/binary_stream.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PodrumR4.dir/build.make CMakeFiles/PodrumR4.dir/cbinarystream/binary_stream.c.o
.PHONY : cbinarystream/binary_stream.c.o

cbinarystream/binary_stream.i: cbinarystream/binary_stream.c.i
.PHONY : cbinarystream/binary_stream.i

# target to preprocess a source file
cbinarystream/binary_stream.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PodrumR4.dir/build.make CMakeFiles/PodrumR4.dir/cbinarystream/binary_stream.c.i
.PHONY : cbinarystream/binary_stream.c.i

cbinarystream/binary_stream.s: cbinarystream/binary_stream.c.s
.PHONY : cbinarystream/binary_stream.s

# target to generate assembly for a file
cbinarystream/binary_stream.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PodrumR4.dir/build.make CMakeFiles/PodrumR4.dir/cbinarystream/binary_stream.c.s
.PHONY : cbinarystream/binary_stream.c.s

cnbt/nbt.o: cnbt/nbt.c.o
.PHONY : cnbt/nbt.o

# target to build an object file
cnbt/nbt.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PodrumR4.dir/build.make CMakeFiles/PodrumR4.dir/cnbt/nbt.c.o
.PHONY : cnbt/nbt.c.o

cnbt/nbt.i: cnbt/nbt.c.i
.PHONY : cnbt/nbt.i

# target to preprocess a source file
cnbt/nbt.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PodrumR4.dir/build.make CMakeFiles/PodrumR4.dir/cnbt/nbt.c.i
.PHONY : cnbt/nbt.c.i

cnbt/nbt.s: cnbt/nbt.c.s
.PHONY : cnbt/nbt.s

# target to generate assembly for a file
cnbt/nbt.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PodrumR4.dir/build.make CMakeFiles/PodrumR4.dir/cnbt/nbt.c.s
.PHONY : cnbt/nbt.c.s

czlibhelper/zlib_helper.o: czlibhelper/zlib_helper.c.o
.PHONY : czlibhelper/zlib_helper.o

# target to build an object file
czlibhelper/zlib_helper.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PodrumR4.dir/build.make CMakeFiles/PodrumR4.dir/czlibhelper/zlib_helper.c.o
.PHONY : czlibhelper/zlib_helper.c.o

czlibhelper/zlib_helper.i: czlibhelper/zlib_helper.c.i
.PHONY : czlibhelper/zlib_helper.i

# target to preprocess a source file
czlibhelper/zlib_helper.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PodrumR4.dir/build.make CMakeFiles/PodrumR4.dir/czlibhelper/zlib_helper.c.i
.PHONY : czlibhelper/zlib_helper.c.i

czlibhelper/zlib_helper.s: czlibhelper/zlib_helper.c.s
.PHONY : czlibhelper/zlib_helper.s

# target to generate assembly for a file
czlibhelper/zlib_helper.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PodrumR4.dir/build.make CMakeFiles/PodrumR4.dir/czlibhelper/zlib_helper.c.s
.PHONY : czlibhelper/zlib_helper.c.s

ecc/ecc.o: ecc/ecc.c.o
.PHONY : ecc/ecc.o

# target to build an object file
ecc/ecc.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PodrumR4.dir/build.make CMakeFiles/PodrumR4.dir/ecc/ecc.c.o
.PHONY : ecc/ecc.c.o

ecc/ecc.i: ecc/ecc.c.i
.PHONY : ecc/ecc.i

# target to preprocess a source file
ecc/ecc.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PodrumR4.dir/build.make CMakeFiles/PodrumR4.dir/ecc/ecc.c.i
.PHONY : ecc/ecc.c.i

ecc/ecc.s: ecc/ecc.c.s
.PHONY : ecc/ecc.s

# target to generate assembly for a file
ecc/ecc.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PodrumR4.dir/build.make CMakeFiles/PodrumR4.dir/ecc/ecc.c.s
.PHONY : ecc/ecc.c.s

miniz/miniz.o: miniz/miniz.c.o
.PHONY : miniz/miniz.o

# target to build an object file
miniz/miniz.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PodrumR4.dir/build.make CMakeFiles/PodrumR4.dir/miniz/miniz.c.o
.PHONY : miniz/miniz.c.o

miniz/miniz.i: miniz/miniz.c.i
.PHONY : miniz/miniz.i

# target to preprocess a source file
miniz/miniz.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PodrumR4.dir/build.make CMakeFiles/PodrumR4.dir/miniz/miniz.c.i
.PHONY : miniz/miniz.c.i

miniz/miniz.s: miniz/miniz.c.s
.PHONY : miniz/miniz.s

# target to generate assembly for a file
miniz/miniz.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PodrumR4.dir/build.make CMakeFiles/PodrumR4.dir/miniz/miniz.c.s
.PHONY : miniz/miniz.c.s

podrum/command/commandmanager.o: podrum/command/commandmanager.c.o
.PHONY : podrum/command/commandmanager.o

# target to build an object file
podrum/command/commandmanager.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PodrumR4.dir/build.make CMakeFiles/PodrumR4.dir/podrum/command/commandmanager.c.o
.PHONY : podrum/command/commandmanager.c.o

podrum/command/commandmanager.i: podrum/command/commandmanager.c.i
.PHONY : podrum/command/commandmanager.i

# target to preprocess a source file
podrum/command/commandmanager.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PodrumR4.dir/build.make CMakeFiles/PodrumR4.dir/podrum/command/commandmanager.c.i
.PHONY : podrum/command/commandmanager.c.i

podrum/command/commandmanager.s: podrum/command/commandmanager.c.s
.PHONY : podrum/command/commandmanager.s

# target to generate assembly for a file
podrum/command/commandmanager.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PodrumR4.dir/build.make CMakeFiles/PodrumR4.dir/podrum/command/commandmanager.c.s
.PHONY : podrum/command/commandmanager.c.s

podrum/misc/base64.o: podrum/misc/base64.c.o
.PHONY : podrum/misc/base64.o

# target to build an object file
podrum/misc/base64.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PodrumR4.dir/build.make CMakeFiles/PodrumR4.dir/podrum/misc/base64.c.o
.PHONY : podrum/misc/base64.c.o

podrum/misc/base64.i: podrum/misc/base64.c.i
.PHONY : podrum/misc/base64.i

# target to preprocess a source file
podrum/misc/base64.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PodrumR4.dir/build.make CMakeFiles/PodrumR4.dir/podrum/misc/base64.c.i
.PHONY : podrum/misc/base64.c.i

podrum/misc/base64.s: podrum/misc/base64.c.s
.PHONY : podrum/misc/base64.s

# target to generate assembly for a file
podrum/misc/base64.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PodrumR4.dir/build.make CMakeFiles/PodrumR4.dir/podrum/misc/base64.c.s
.PHONY : podrum/misc/base64.c.s

podrum/misc/json.o: podrum/misc/json.c.o
.PHONY : podrum/misc/json.o

# target to build an object file
podrum/misc/json.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PodrumR4.dir/build.make CMakeFiles/PodrumR4.dir/podrum/misc/json.c.o
.PHONY : podrum/misc/json.c.o

podrum/misc/json.i: podrum/misc/json.c.i
.PHONY : podrum/misc/json.i

# target to preprocess a source file
podrum/misc/json.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PodrumR4.dir/build.make CMakeFiles/PodrumR4.dir/podrum/misc/json.c.i
.PHONY : podrum/misc/json.c.i

podrum/misc/json.s: podrum/misc/json.c.s
.PHONY : podrum/misc/json.s

# target to generate assembly for a file
podrum/misc/json.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PodrumR4.dir/build.make CMakeFiles/PodrumR4.dir/podrum/misc/json.c.s
.PHONY : podrum/misc/json.c.s

podrum/misc/jwt.o: podrum/misc/jwt.c.o
.PHONY : podrum/misc/jwt.o

# target to build an object file
podrum/misc/jwt.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PodrumR4.dir/build.make CMakeFiles/PodrumR4.dir/podrum/misc/jwt.c.o
.PHONY : podrum/misc/jwt.c.o

podrum/misc/jwt.i: podrum/misc/jwt.c.i
.PHONY : podrum/misc/jwt.i

# target to preprocess a source file
podrum/misc/jwt.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PodrumR4.dir/build.make CMakeFiles/PodrumR4.dir/podrum/misc/jwt.c.i
.PHONY : podrum/misc/jwt.c.i

podrum/misc/jwt.s: podrum/misc/jwt.c.s
.PHONY : podrum/misc/jwt.s

# target to generate assembly for a file
podrum/misc/jwt.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PodrumR4.dir/build.make CMakeFiles/PodrumR4.dir/podrum/misc/jwt.c.s
.PHONY : podrum/misc/jwt.c.s

podrum/misc/logger.o: podrum/misc/logger.c.o
.PHONY : podrum/misc/logger.o

# target to build an object file
podrum/misc/logger.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PodrumR4.dir/build.make CMakeFiles/PodrumR4.dir/podrum/misc/logger.c.o
.PHONY : podrum/misc/logger.c.o

podrum/misc/logger.i: podrum/misc/logger.c.i
.PHONY : podrum/misc/logger.i

# target to preprocess a source file
podrum/misc/logger.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PodrumR4.dir/build.make CMakeFiles/PodrumR4.dir/podrum/misc/logger.c.i
.PHONY : podrum/misc/logger.c.i

podrum/misc/logger.s: podrum/misc/logger.c.s
.PHONY : podrum/misc/logger.s

# target to generate assembly for a file
podrum/misc/logger.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PodrumR4.dir/build.make CMakeFiles/PodrumR4.dir/podrum/misc/logger.c.s
.PHONY : podrum/misc/logger.c.s

podrum/misc/resourcemanager.o: podrum/misc/resourcemanager.c.o
.PHONY : podrum/misc/resourcemanager.o

# target to build an object file
podrum/misc/resourcemanager.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PodrumR4.dir/build.make CMakeFiles/PodrumR4.dir/podrum/misc/resourcemanager.c.o
.PHONY : podrum/misc/resourcemanager.c.o

podrum/misc/resourcemanager.i: podrum/misc/resourcemanager.c.i
.PHONY : podrum/misc/resourcemanager.i

# target to preprocess a source file
podrum/misc/resourcemanager.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PodrumR4.dir/build.make CMakeFiles/PodrumR4.dir/podrum/misc/resourcemanager.c.i
.PHONY : podrum/misc/resourcemanager.c.i

podrum/misc/resourcemanager.s: podrum/misc/resourcemanager.c.s
.PHONY : podrum/misc/resourcemanager.s

# target to generate assembly for a file
podrum/misc/resourcemanager.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PodrumR4.dir/build.make CMakeFiles/PodrumR4.dir/podrum/misc/resourcemanager.c.s
.PHONY : podrum/misc/resourcemanager.c.s

podrum/network/minecraft/mchandler.o: podrum/network/minecraft/mchandler.c.o
.PHONY : podrum/network/minecraft/mchandler.o

# target to build an object file
podrum/network/minecraft/mchandler.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PodrumR4.dir/build.make CMakeFiles/PodrumR4.dir/podrum/network/minecraft/mchandler.c.o
.PHONY : podrum/network/minecraft/mchandler.c.o

podrum/network/minecraft/mchandler.i: podrum/network/minecraft/mchandler.c.i
.PHONY : podrum/network/minecraft/mchandler.i

# target to preprocess a source file
podrum/network/minecraft/mchandler.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PodrumR4.dir/build.make CMakeFiles/PodrumR4.dir/podrum/network/minecraft/mchandler.c.i
.PHONY : podrum/network/minecraft/mchandler.c.i

podrum/network/minecraft/mchandler.s: podrum/network/minecraft/mchandler.c.s
.PHONY : podrum/network/minecraft/mchandler.s

# target to generate assembly for a file
podrum/network/minecraft/mchandler.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PodrumR4.dir/build.make CMakeFiles/PodrumR4.dir/podrum/network/minecraft/mchandler.c.s
.PHONY : podrum/network/minecraft/mchandler.c.s

podrum/network/minecraft/mcmapping.o: podrum/network/minecraft/mcmapping.c.o
.PHONY : podrum/network/minecraft/mcmapping.o

# target to build an object file
podrum/network/minecraft/mcmapping.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PodrumR4.dir/build.make CMakeFiles/PodrumR4.dir/podrum/network/minecraft/mcmapping.c.o
.PHONY : podrum/network/minecraft/mcmapping.c.o

podrum/network/minecraft/mcmapping.i: podrum/network/minecraft/mcmapping.c.i
.PHONY : podrum/network/minecraft/mcmapping.i

# target to preprocess a source file
podrum/network/minecraft/mcmapping.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PodrumR4.dir/build.make CMakeFiles/PodrumR4.dir/podrum/network/minecraft/mcmapping.c.i
.PHONY : podrum/network/minecraft/mcmapping.c.i

podrum/network/minecraft/mcmapping.s: podrum/network/minecraft/mcmapping.c.s
.PHONY : podrum/network/minecraft/mcmapping.s

# target to generate assembly for a file
podrum/network/minecraft/mcmapping.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PodrumR4.dir/build.make CMakeFiles/PodrumR4.dir/podrum/network/minecraft/mcmapping.c.s
.PHONY : podrum/network/minecraft/mcmapping.c.s

podrum/network/minecraft/mcmisc.o: podrum/network/minecraft/mcmisc.c.o
.PHONY : podrum/network/minecraft/mcmisc.o

# target to build an object file
podrum/network/minecraft/mcmisc.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PodrumR4.dir/build.make CMakeFiles/PodrumR4.dir/podrum/network/minecraft/mcmisc.c.o
.PHONY : podrum/network/minecraft/mcmisc.c.o

podrum/network/minecraft/mcmisc.i: podrum/network/minecraft/mcmisc.c.i
.PHONY : podrum/network/minecraft/mcmisc.i

# target to preprocess a source file
podrum/network/minecraft/mcmisc.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PodrumR4.dir/build.make CMakeFiles/PodrumR4.dir/podrum/network/minecraft/mcmisc.c.i
.PHONY : podrum/network/minecraft/mcmisc.c.i

podrum/network/minecraft/mcmisc.s: podrum/network/minecraft/mcmisc.c.s
.PHONY : podrum/network/minecraft/mcmisc.s

# target to generate assembly for a file
podrum/network/minecraft/mcmisc.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PodrumR4.dir/build.make CMakeFiles/PodrumR4.dir/podrum/network/minecraft/mcmisc.c.s
.PHONY : podrum/network/minecraft/mcmisc.c.s

podrum/network/minecraft/mcpackets.o: podrum/network/minecraft/mcpackets.c.o
.PHONY : podrum/network/minecraft/mcpackets.o

# target to build an object file
podrum/network/minecraft/mcpackets.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PodrumR4.dir/build.make CMakeFiles/PodrumR4.dir/podrum/network/minecraft/mcpackets.c.o
.PHONY : podrum/network/minecraft/mcpackets.c.o

podrum/network/minecraft/mcpackets.i: podrum/network/minecraft/mcpackets.c.i
.PHONY : podrum/network/minecraft/mcpackets.i

# target to preprocess a source file
podrum/network/minecraft/mcpackets.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PodrumR4.dir/build.make CMakeFiles/PodrumR4.dir/podrum/network/minecraft/mcpackets.c.i
.PHONY : podrum/network/minecraft/mcpackets.c.i

podrum/network/minecraft/mcpackets.s: podrum/network/minecraft/mcpackets.c.s
.PHONY : podrum/network/minecraft/mcpackets.s

# target to generate assembly for a file
podrum/network/minecraft/mcpackets.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PodrumR4.dir/build.make CMakeFiles/PodrumR4.dir/podrum/network/minecraft/mcpackets.c.s
.PHONY : podrum/network/minecraft/mcpackets.c.s

podrum/network/minecraft/mcplayer.o: podrum/network/minecraft/mcplayer.c.o
.PHONY : podrum/network/minecraft/mcplayer.o

# target to build an object file
podrum/network/minecraft/mcplayer.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PodrumR4.dir/build.make CMakeFiles/PodrumR4.dir/podrum/network/minecraft/mcplayer.c.o
.PHONY : podrum/network/minecraft/mcplayer.c.o

podrum/network/minecraft/mcplayer.i: podrum/network/minecraft/mcplayer.c.i
.PHONY : podrum/network/minecraft/mcplayer.i

# target to preprocess a source file
podrum/network/minecraft/mcplayer.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PodrumR4.dir/build.make CMakeFiles/PodrumR4.dir/podrum/network/minecraft/mcplayer.c.i
.PHONY : podrum/network/minecraft/mcplayer.c.i

podrum/network/minecraft/mcplayer.s: podrum/network/minecraft/mcplayer.c.s
.PHONY : podrum/network/minecraft/mcplayer.s

# target to generate assembly for a file
podrum/network/minecraft/mcplayer.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PodrumR4.dir/build.make CMakeFiles/PodrumR4.dir/podrum/network/minecraft/mcplayer.c.s
.PHONY : podrum/network/minecraft/mcplayer.c.s

podrum/network/minecraft/mcplayermanager.o: podrum/network/minecraft/mcplayermanager.c.o
.PHONY : podrum/network/minecraft/mcplayermanager.o

# target to build an object file
podrum/network/minecraft/mcplayermanager.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PodrumR4.dir/build.make CMakeFiles/PodrumR4.dir/podrum/network/minecraft/mcplayermanager.c.o
.PHONY : podrum/network/minecraft/mcplayermanager.c.o

podrum/network/minecraft/mcplayermanager.i: podrum/network/minecraft/mcplayermanager.c.i
.PHONY : podrum/network/minecraft/mcplayermanager.i

# target to preprocess a source file
podrum/network/minecraft/mcplayermanager.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PodrumR4.dir/build.make CMakeFiles/PodrumR4.dir/podrum/network/minecraft/mcplayermanager.c.i
.PHONY : podrum/network/minecraft/mcplayermanager.c.i

podrum/network/minecraft/mcplayermanager.s: podrum/network/minecraft/mcplayermanager.c.s
.PHONY : podrum/network/minecraft/mcplayermanager.s

# target to generate assembly for a file
podrum/network/minecraft/mcplayermanager.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PodrumR4.dir/build.make CMakeFiles/PodrumR4.dir/podrum/network/minecraft/mcplayermanager.c.s
.PHONY : podrum/network/minecraft/mcplayermanager.c.s

podrum/network/raknet/rakhandler.o: podrum/network/raknet/rakhandler.c.o
.PHONY : podrum/network/raknet/rakhandler.o

# target to build an object file
podrum/network/raknet/rakhandler.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PodrumR4.dir/build.make CMakeFiles/PodrumR4.dir/podrum/network/raknet/rakhandler.c.o
.PHONY : podrum/network/raknet/rakhandler.c.o

podrum/network/raknet/rakhandler.i: podrum/network/raknet/rakhandler.c.i
.PHONY : podrum/network/raknet/rakhandler.i

# target to preprocess a source file
podrum/network/raknet/rakhandler.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PodrumR4.dir/build.make CMakeFiles/PodrumR4.dir/podrum/network/raknet/rakhandler.c.i
.PHONY : podrum/network/raknet/rakhandler.c.i

podrum/network/raknet/rakhandler.s: podrum/network/raknet/rakhandler.c.s
.PHONY : podrum/network/raknet/rakhandler.s

# target to generate assembly for a file
podrum/network/raknet/rakhandler.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PodrumR4.dir/build.make CMakeFiles/PodrumR4.dir/podrum/network/raknet/rakhandler.c.s
.PHONY : podrum/network/raknet/rakhandler.c.s

podrum/network/raknet/rakinternal.o: podrum/network/raknet/rakinternal.c.o
.PHONY : podrum/network/raknet/rakinternal.o

# target to build an object file
podrum/network/raknet/rakinternal.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PodrumR4.dir/build.make CMakeFiles/PodrumR4.dir/podrum/network/raknet/rakinternal.c.o
.PHONY : podrum/network/raknet/rakinternal.c.o

podrum/network/raknet/rakinternal.i: podrum/network/raknet/rakinternal.c.i
.PHONY : podrum/network/raknet/rakinternal.i

# target to preprocess a source file
podrum/network/raknet/rakinternal.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PodrumR4.dir/build.make CMakeFiles/PodrumR4.dir/podrum/network/raknet/rakinternal.c.i
.PHONY : podrum/network/raknet/rakinternal.c.i

podrum/network/raknet/rakinternal.s: podrum/network/raknet/rakinternal.c.s
.PHONY : podrum/network/raknet/rakinternal.s

# target to generate assembly for a file
podrum/network/raknet/rakinternal.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PodrumR4.dir/build.make CMakeFiles/PodrumR4.dir/podrum/network/raknet/rakinternal.c.s
.PHONY : podrum/network/raknet/rakinternal.c.s

podrum/network/raknet/rakmisc.o: podrum/network/raknet/rakmisc.c.o
.PHONY : podrum/network/raknet/rakmisc.o

# target to build an object file
podrum/network/raknet/rakmisc.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PodrumR4.dir/build.make CMakeFiles/PodrumR4.dir/podrum/network/raknet/rakmisc.c.o
.PHONY : podrum/network/raknet/rakmisc.c.o

podrum/network/raknet/rakmisc.i: podrum/network/raknet/rakmisc.c.i
.PHONY : podrum/network/raknet/rakmisc.i

# target to preprocess a source file
podrum/network/raknet/rakmisc.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PodrumR4.dir/build.make CMakeFiles/PodrumR4.dir/podrum/network/raknet/rakmisc.c.i
.PHONY : podrum/network/raknet/rakmisc.c.i

podrum/network/raknet/rakmisc.s: podrum/network/raknet/rakmisc.c.s
.PHONY : podrum/network/raknet/rakmisc.s

# target to generate assembly for a file
podrum/network/raknet/rakmisc.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PodrumR4.dir/build.make CMakeFiles/PodrumR4.dir/podrum/network/raknet/rakmisc.c.s
.PHONY : podrum/network/raknet/rakmisc.c.s

podrum/network/raknet/rakpacket.o: podrum/network/raknet/rakpacket.c.o
.PHONY : podrum/network/raknet/rakpacket.o

# target to build an object file
podrum/network/raknet/rakpacket.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PodrumR4.dir/build.make CMakeFiles/PodrumR4.dir/podrum/network/raknet/rakpacket.c.o
.PHONY : podrum/network/raknet/rakpacket.c.o

podrum/network/raknet/rakpacket.i: podrum/network/raknet/rakpacket.c.i
.PHONY : podrum/network/raknet/rakpacket.i

# target to preprocess a source file
podrum/network/raknet/rakpacket.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PodrumR4.dir/build.make CMakeFiles/PodrumR4.dir/podrum/network/raknet/rakpacket.c.i
.PHONY : podrum/network/raknet/rakpacket.c.i

podrum/network/raknet/rakpacket.s: podrum/network/raknet/rakpacket.c.s
.PHONY : podrum/network/raknet/rakpacket.s

# target to generate assembly for a file
podrum/network/raknet/rakpacket.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PodrumR4.dir/build.make CMakeFiles/PodrumR4.dir/podrum/network/raknet/rakpacket.c.s
.PHONY : podrum/network/raknet/rakpacket.c.s

podrum/network/raknet/rakserver.o: podrum/network/raknet/rakserver.c.o
.PHONY : podrum/network/raknet/rakserver.o

# target to build an object file
podrum/network/raknet/rakserver.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PodrumR4.dir/build.make CMakeFiles/PodrumR4.dir/podrum/network/raknet/rakserver.c.o
.PHONY : podrum/network/raknet/rakserver.c.o

podrum/network/raknet/rakserver.i: podrum/network/raknet/rakserver.c.i
.PHONY : podrum/network/raknet/rakserver.i

# target to preprocess a source file
podrum/network/raknet/rakserver.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PodrumR4.dir/build.make CMakeFiles/PodrumR4.dir/podrum/network/raknet/rakserver.c.i
.PHONY : podrum/network/raknet/rakserver.c.i

podrum/network/raknet/rakserver.s: podrum/network/raknet/rakserver.c.s
.PHONY : podrum/network/raknet/rakserver.s

# target to generate assembly for a file
podrum/network/raknet/rakserver.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PodrumR4.dir/build.make CMakeFiles/PodrumR4.dir/podrum/network/raknet/rakserver.c.s
.PHONY : podrum/network/raknet/rakserver.c.s

podrum/network/raknet/socket.o: podrum/network/raknet/socket.c.o
.PHONY : podrum/network/raknet/socket.o

# target to build an object file
podrum/network/raknet/socket.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PodrumR4.dir/build.make CMakeFiles/PodrumR4.dir/podrum/network/raknet/socket.c.o
.PHONY : podrum/network/raknet/socket.c.o

podrum/network/raknet/socket.i: podrum/network/raknet/socket.c.i
.PHONY : podrum/network/raknet/socket.i

# target to preprocess a source file
podrum/network/raknet/socket.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PodrumR4.dir/build.make CMakeFiles/PodrumR4.dir/podrum/network/raknet/socket.c.i
.PHONY : podrum/network/raknet/socket.c.i

podrum/network/raknet/socket.s: podrum/network/raknet/socket.c.s
.PHONY : podrum/network/raknet/socket.s

# target to generate assembly for a file
podrum/network/raknet/socket.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PodrumR4.dir/build.make CMakeFiles/PodrumR4.dir/podrum/network/raknet/socket.c.s
.PHONY : podrum/network/raknet/socket.c.s

podrum/queue.o: podrum/queue.c.o
.PHONY : podrum/queue.o

# target to build an object file
podrum/queue.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PodrumR4.dir/build.make CMakeFiles/PodrumR4.dir/podrum/queue.c.o
.PHONY : podrum/queue.c.o

podrum/queue.i: podrum/queue.c.i
.PHONY : podrum/queue.i

# target to preprocess a source file
podrum/queue.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PodrumR4.dir/build.make CMakeFiles/PodrumR4.dir/podrum/queue.c.i
.PHONY : podrum/queue.c.i

podrum/queue.s: podrum/queue.c.s
.PHONY : podrum/queue.s

# target to generate assembly for a file
podrum/queue.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PodrumR4.dir/build.make CMakeFiles/PodrumR4.dir/podrum/queue.c.s
.PHONY : podrum/queue.c.s

podrum/server.o: podrum/server.c.o
.PHONY : podrum/server.o

# target to build an object file
podrum/server.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PodrumR4.dir/build.make CMakeFiles/PodrumR4.dir/podrum/server.c.o
.PHONY : podrum/server.c.o

podrum/server.i: podrum/server.c.i
.PHONY : podrum/server.i

# target to preprocess a source file
podrum/server.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PodrumR4.dir/build.make CMakeFiles/PodrumR4.dir/podrum/server.c.i
.PHONY : podrum/server.c.i

podrum/server.s: podrum/server.c.s
.PHONY : podrum/server.s

# target to generate assembly for a file
podrum/server.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PodrumR4.dir/build.make CMakeFiles/PodrumR4.dir/podrum/server.c.s
.PHONY : podrum/server.c.s

podrum/worker.o: podrum/worker.c.o
.PHONY : podrum/worker.o

# target to build an object file
podrum/worker.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PodrumR4.dir/build.make CMakeFiles/PodrumR4.dir/podrum/worker.c.o
.PHONY : podrum/worker.c.o

podrum/worker.i: podrum/worker.c.i
.PHONY : podrum/worker.i

# target to preprocess a source file
podrum/worker.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PodrumR4.dir/build.make CMakeFiles/PodrumR4.dir/podrum/worker.c.i
.PHONY : podrum/worker.c.i

podrum/worker.s: podrum/worker.c.s
.PHONY : podrum/worker.s

# target to generate assembly for a file
podrum/worker.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PodrumR4.dir/build.make CMakeFiles/PodrumR4.dir/podrum/worker.c.s
.PHONY : podrum/worker.c.s

podrum/world/chunk/blockstorage.o: podrum/world/chunk/blockstorage.c.o
.PHONY : podrum/world/chunk/blockstorage.o

# target to build an object file
podrum/world/chunk/blockstorage.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PodrumR4.dir/build.make CMakeFiles/PodrumR4.dir/podrum/world/chunk/blockstorage.c.o
.PHONY : podrum/world/chunk/blockstorage.c.o

podrum/world/chunk/blockstorage.i: podrum/world/chunk/blockstorage.c.i
.PHONY : podrum/world/chunk/blockstorage.i

# target to preprocess a source file
podrum/world/chunk/blockstorage.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PodrumR4.dir/build.make CMakeFiles/PodrumR4.dir/podrum/world/chunk/blockstorage.c.i
.PHONY : podrum/world/chunk/blockstorage.c.i

podrum/world/chunk/blockstorage.s: podrum/world/chunk/blockstorage.c.s
.PHONY : podrum/world/chunk/blockstorage.s

# target to generate assembly for a file
podrum/world/chunk/blockstorage.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PodrumR4.dir/build.make CMakeFiles/PodrumR4.dir/podrum/world/chunk/blockstorage.c.s
.PHONY : podrum/world/chunk/blockstorage.c.s

podrum/world/chunk/chunk.o: podrum/world/chunk/chunk.c.o
.PHONY : podrum/world/chunk/chunk.o

# target to build an object file
podrum/world/chunk/chunk.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PodrumR4.dir/build.make CMakeFiles/PodrumR4.dir/podrum/world/chunk/chunk.c.o
.PHONY : podrum/world/chunk/chunk.c.o

podrum/world/chunk/chunk.i: podrum/world/chunk/chunk.c.i
.PHONY : podrum/world/chunk/chunk.i

# target to preprocess a source file
podrum/world/chunk/chunk.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PodrumR4.dir/build.make CMakeFiles/PodrumR4.dir/podrum/world/chunk/chunk.c.i
.PHONY : podrum/world/chunk/chunk.c.i

podrum/world/chunk/chunk.s: podrum/world/chunk/chunk.c.s
.PHONY : podrum/world/chunk/chunk.s

# target to generate assembly for a file
podrum/world/chunk/chunk.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PodrumR4.dir/build.make CMakeFiles/PodrumR4.dir/podrum/world/chunk/chunk.c.s
.PHONY : podrum/world/chunk/chunk.c.s

podrum/world/chunk/subchunk.o: podrum/world/chunk/subchunk.c.o
.PHONY : podrum/world/chunk/subchunk.o

# target to build an object file
podrum/world/chunk/subchunk.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PodrumR4.dir/build.make CMakeFiles/PodrumR4.dir/podrum/world/chunk/subchunk.c.o
.PHONY : podrum/world/chunk/subchunk.c.o

podrum/world/chunk/subchunk.i: podrum/world/chunk/subchunk.c.i
.PHONY : podrum/world/chunk/subchunk.i

# target to preprocess a source file
podrum/world/chunk/subchunk.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PodrumR4.dir/build.make CMakeFiles/PodrumR4.dir/podrum/world/chunk/subchunk.c.i
.PHONY : podrum/world/chunk/subchunk.c.i

podrum/world/chunk/subchunk.s: podrum/world/chunk/subchunk.c.s
.PHONY : podrum/world/chunk/subchunk.s

# target to generate assembly for a file
podrum/world/chunk/subchunk.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PodrumR4.dir/build.make CMakeFiles/PodrumR4.dir/podrum/world/chunk/subchunk.c.s
.PHONY : podrum/world/chunk/subchunk.c.s

podrum/world/format/anvil/region.o: podrum/world/format/anvil/region.c.o
.PHONY : podrum/world/format/anvil/region.o

# target to build an object file
podrum/world/format/anvil/region.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PodrumR4.dir/build.make CMakeFiles/PodrumR4.dir/podrum/world/format/anvil/region.c.o
.PHONY : podrum/world/format/anvil/region.c.o

podrum/world/format/anvil/region.i: podrum/world/format/anvil/region.c.i
.PHONY : podrum/world/format/anvil/region.i

# target to preprocess a source file
podrum/world/format/anvil/region.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PodrumR4.dir/build.make CMakeFiles/PodrumR4.dir/podrum/world/format/anvil/region.c.i
.PHONY : podrum/world/format/anvil/region.c.i

podrum/world/format/anvil/region.s: podrum/world/format/anvil/region.c.s
.PHONY : podrum/world/format/anvil/region.s

# target to generate assembly for a file
podrum/world/format/anvil/region.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PodrumR4.dir/build.make CMakeFiles/PodrumR4.dir/podrum/world/format/anvil/region.c.s
.PHONY : podrum/world/format/anvil/region.c.s

sha256/sha256.o: sha256/sha256.c.o
.PHONY : sha256/sha256.o

# target to build an object file
sha256/sha256.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PodrumR4.dir/build.make CMakeFiles/PodrumR4.dir/sha256/sha256.c.o
.PHONY : sha256/sha256.c.o

sha256/sha256.i: sha256/sha256.c.i
.PHONY : sha256/sha256.i

# target to preprocess a source file
sha256/sha256.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PodrumR4.dir/build.make CMakeFiles/PodrumR4.dir/sha256/sha256.c.i
.PHONY : sha256/sha256.c.i

sha256/sha256.s: sha256/sha256.c.s
.PHONY : sha256/sha256.s

# target to generate assembly for a file
sha256/sha256.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PodrumR4.dir/build.make CMakeFiles/PodrumR4.dir/sha256/sha256.c.s
.PHONY : sha256/sha256.c.s

tinyaes/aes.o: tinyaes/aes.c.o
.PHONY : tinyaes/aes.o

# target to build an object file
tinyaes/aes.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PodrumR4.dir/build.make CMakeFiles/PodrumR4.dir/tinyaes/aes.c.o
.PHONY : tinyaes/aes.c.o

tinyaes/aes.i: tinyaes/aes.c.i
.PHONY : tinyaes/aes.i

# target to preprocess a source file
tinyaes/aes.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PodrumR4.dir/build.make CMakeFiles/PodrumR4.dir/tinyaes/aes.c.i
.PHONY : tinyaes/aes.c.i

tinyaes/aes.s: tinyaes/aes.c.s
.PHONY : tinyaes/aes.s

# target to generate assembly for a file
tinyaes/aes.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PodrumR4.dir/build.make CMakeFiles/PodrumR4.dir/tinyaes/aes.c.s
.PHONY : tinyaes/aes.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... PodrumR4"
	@echo "... cbinarystream/binary_stream.o"
	@echo "... cbinarystream/binary_stream.i"
	@echo "... cbinarystream/binary_stream.s"
	@echo "... cnbt/nbt.o"
	@echo "... cnbt/nbt.i"
	@echo "... cnbt/nbt.s"
	@echo "... czlibhelper/zlib_helper.o"
	@echo "... czlibhelper/zlib_helper.i"
	@echo "... czlibhelper/zlib_helper.s"
	@echo "... ecc/ecc.o"
	@echo "... ecc/ecc.i"
	@echo "... ecc/ecc.s"
	@echo "... miniz/miniz.o"
	@echo "... miniz/miniz.i"
	@echo "... miniz/miniz.s"
	@echo "... podrum/command/commandmanager.o"
	@echo "... podrum/command/commandmanager.i"
	@echo "... podrum/command/commandmanager.s"
	@echo "... podrum/misc/base64.o"
	@echo "... podrum/misc/base64.i"
	@echo "... podrum/misc/base64.s"
	@echo "... podrum/misc/json.o"
	@echo "... podrum/misc/json.i"
	@echo "... podrum/misc/json.s"
	@echo "... podrum/misc/jwt.o"
	@echo "... podrum/misc/jwt.i"
	@echo "... podrum/misc/jwt.s"
	@echo "... podrum/misc/logger.o"
	@echo "... podrum/misc/logger.i"
	@echo "... podrum/misc/logger.s"
	@echo "... podrum/misc/resourcemanager.o"
	@echo "... podrum/misc/resourcemanager.i"
	@echo "... podrum/misc/resourcemanager.s"
	@echo "... podrum/network/minecraft/mchandler.o"
	@echo "... podrum/network/minecraft/mchandler.i"
	@echo "... podrum/network/minecraft/mchandler.s"
	@echo "... podrum/network/minecraft/mcmapping.o"
	@echo "... podrum/network/minecraft/mcmapping.i"
	@echo "... podrum/network/minecraft/mcmapping.s"
	@echo "... podrum/network/minecraft/mcmisc.o"
	@echo "... podrum/network/minecraft/mcmisc.i"
	@echo "... podrum/network/minecraft/mcmisc.s"
	@echo "... podrum/network/minecraft/mcpackets.o"
	@echo "... podrum/network/minecraft/mcpackets.i"
	@echo "... podrum/network/minecraft/mcpackets.s"
	@echo "... podrum/network/minecraft/mcplayer.o"
	@echo "... podrum/network/minecraft/mcplayer.i"
	@echo "... podrum/network/minecraft/mcplayer.s"
	@echo "... podrum/network/minecraft/mcplayermanager.o"
	@echo "... podrum/network/minecraft/mcplayermanager.i"
	@echo "... podrum/network/minecraft/mcplayermanager.s"
	@echo "... podrum/network/raknet/rakhandler.o"
	@echo "... podrum/network/raknet/rakhandler.i"
	@echo "... podrum/network/raknet/rakhandler.s"
	@echo "... podrum/network/raknet/rakinternal.o"
	@echo "... podrum/network/raknet/rakinternal.i"
	@echo "... podrum/network/raknet/rakinternal.s"
	@echo "... podrum/network/raknet/rakmisc.o"
	@echo "... podrum/network/raknet/rakmisc.i"
	@echo "... podrum/network/raknet/rakmisc.s"
	@echo "... podrum/network/raknet/rakpacket.o"
	@echo "... podrum/network/raknet/rakpacket.i"
	@echo "... podrum/network/raknet/rakpacket.s"
	@echo "... podrum/network/raknet/rakserver.o"
	@echo "... podrum/network/raknet/rakserver.i"
	@echo "... podrum/network/raknet/rakserver.s"
	@echo "... podrum/network/raknet/socket.o"
	@echo "... podrum/network/raknet/socket.i"
	@echo "... podrum/network/raknet/socket.s"
	@echo "... podrum/queue.o"
	@echo "... podrum/queue.i"
	@echo "... podrum/queue.s"
	@echo "... podrum/server.o"
	@echo "... podrum/server.i"
	@echo "... podrum/server.s"
	@echo "... podrum/worker.o"
	@echo "... podrum/worker.i"
	@echo "... podrum/worker.s"
	@echo "... podrum/world/chunk/blockstorage.o"
	@echo "... podrum/world/chunk/blockstorage.i"
	@echo "... podrum/world/chunk/blockstorage.s"
	@echo "... podrum/world/chunk/chunk.o"
	@echo "... podrum/world/chunk/chunk.i"
	@echo "... podrum/world/chunk/chunk.s"
	@echo "... podrum/world/chunk/subchunk.o"
	@echo "... podrum/world/chunk/subchunk.i"
	@echo "... podrum/world/chunk/subchunk.s"
	@echo "... podrum/world/format/anvil/region.o"
	@echo "... podrum/world/format/anvil/region.i"
	@echo "... podrum/world/format/anvil/region.s"
	@echo "... sha256/sha256.o"
	@echo "... sha256/sha256.i"
	@echo "... sha256/sha256.s"
	@echo "... tinyaes/aes.o"
	@echo "... tinyaes/aes.i"
	@echo "... tinyaes/aes.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

